### ISSUE TITLE
Attribute schemaUrl was typed schemaURl

### ISSUE THREAD

**Issue by davidlima** [haoliangyu/gtran-kml#1]
https://github.com/haoliangyu/gtran-kml/blob/6c7abb384ca6aa0939a06ee79c063e651f6f1e6c/src/script.js#L198

This was causing an error in my script, and checking the documentation I believe needs to be changed to "schemaUrl".
<SchemaData schemaUrl="anyURI">
https://developers.google.com/kml/documentation/kmlreference

**Comment by haoliangyu** [comment]
Thanks for digging into the bug! It seems I used to a bad example to test the code. I will fix this and publish the update very soon.

**Comment by haoliangyu** [comment]
fix with version v1.1.12
