### ISSUE TITLE
Wrong coordinates parse on some kmls.

### ISSUE THREAD

**Issue by sersanchus** [haoliangyu/gtran-kml#15]
The function getCoordinates doesn't parse well the linestring coordinates on kml files like this:

    <Placemark>
      <description><![CDATA[Unknown Line Type<BR><BR><B>LENGTH</B> = 608.79 km<BR><B>BEARING</B> = 280.9031°]]></description>
      <name>line0</name>
      <styleUrl>#line1</styleUrl>
      <LineString>
        <coordinates>
          -1.7746464741,38.2362742315,0
          -3.2438886712,37.6742165982,0
          -5.1753643685,37.5428846948,0
          -6.6776232442,37.8576881050,0
          -7.4865318696,38.4443034260,0
          -7.6681236019,38.9746246036,0
        </coordinates>
      </LineString>
    </Placemark>

Every space in front of a coordinate turns out in a NaN, NaN position.

**Comment by haoliangyu** [comment]
@sersanchus Please check with the new release (v1.4.5). It should fix the bug.
