### ISSUE TITLE
Multiple symbols with multiple Placemarks on the KML file

### ISSUE THREAD

**Issue by dssoma** [haoliangyu/gtran-kml#2]
[test.txt](https://github.com/haoliangyu/gtran-kml/files/1739115/test.txt)

I need to generate this kind of kml file with my dynamic data.Is it possible with this package?If it is then how?please help.

**Comment by haoliangyu** [comment]
**What this library can do**

* create a KML file or a string with the KML content with the input geojson
* save all point properties into the kml
* specify one property to be the feature name in the kml
* specify a symbol for all features (of the same geometry type)

**What this library cannot do yet**

* (conditionally) specify a symbol to each feature in the kml. Not sure if that's what you need.

**Example**

``` javascript
const kml = require('gtran-kml');

const geojson = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-122.0856545755255,37.42243077405461]
      },
      properties: {
        name: 'Roll over this icon'
      }
    }
  ]
}

const pointSymbol = {
  icon: 'http://maps.google.com/mapfiles/kml/paddle/wht-blank.png'
};

kml
  // save a kml file name point.kml
  .fromGeoJson(geojson, 'point.kml', {
    // point symbol for the layer
    symbol: pointSymbol,
    // specify which property to be the point name
    name: 'name'
  });
```

This code produces [point.txt](https://github.com/haoliangyu/gtran-kml/files/1742900/point.txt) <- change the extension to kml.
